# Generated by Django 6.0.2 on 2026-05-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=90)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
