# Generated by Django 6.0.2 on 2026-05-13 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('uuid_public', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_producto', models.IntegerField()),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('stock_maximo', models.IntegerField(default=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('id_proveedor', models.IntegerField()),
                ('cantidad_entradas', models.IntegerField(default=0)),
                ('cantidad_salidas', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
