# Generated by Django 6.0.2 on 2026-05-14 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, help_text='Descripción del reporte...', max_length=150)),
                ('tipo', models.CharField(db_index=True, default='models', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('usuario_creacion', models.CharField(default='nombre_usuario', max_length=30)),
                ('activo_tf', models.BooleanField(default=True)),
                ('total_monto', models.DecimalField(decimal_places=2, default=0, help_text='Total monetario calculado (si aplica)', max_digits=12)),
                ('parametros', models.JSONField(blank=True, help_text='Filtros dinámicos usados para generar el reporte', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('reportes', models.ManyToManyField(related_name='categorias', to='reportes.reporte')),
            ],
        ),
    ]
